### ISSUE TITLE
Import all

### ISSUE THREAD

**Issue by tft-kaare** [TromsFylkestrafikk/ragnarok#43]
## Problem / motivation
We need better tools for how and what chunks are imported. We need option for overwrite or keep existing of imported data during import. We need the ability to specify a range of chunks (from ID to ID), we need a command for importing everything not yet imported, etc.

## Suggested resolution

UI: Expand the available tools in the upper right of the chunk listing with a collapsible/popup-alike UI that presents the user to all operations for data set:
- Fetch/delete/import selection or range (see below)
- Option with overwrite existing (re-fetch, re-import). Maybe separate force-option for fetch/import
- Specify range of IDs (from, to) to operate on.
- Option to import chunks that has a given state (new, failed, finished)

API: Make sure the back-end operations allows us to easily create cli frontend for the same operations as well.

## TODO

- [x] Move chunk mass operation as patch callback in sink controller
- [x] Add single chunk operations in ChunkController.
- [x] Implement use of [ ] Force – i.e. don't destroy unless forced.

**Comment by tft-kaare** [comment]
With #44 in place, we are now able to select status on fetch and import. We should use these params in combination with the desired filters.

So for user input we need:
- Operation (fetch, delete fetched, import, delete import)
- Override existing fetch/import
- Choice between checkbox selection or range (see below) of chunks to operate on
- Range (From ID, to ID) of selection to operate on.

UI for specification of ID range should only be visible when user selects 'range'. In this case, the checkbox selection should be ignored.

**Comment by tft-kaare** [comment]
Now we have duplicate form inputs for filtering and what to operate on. It's weird.

I think we should drop the four input fields in the operation form: from/to chunk and fetch/import status. Instead use the existing selection and toggle between 'operate on entire filtered set' or 'selected chunks from filtered set'.
